### ISSUE TITLE
개발 환경 셋업

### ISSUE THREAD

**Issue by paengjiwoo** [paengjiwoo/Docify#1]
# 📁 Todo

- [ ] database 환경 셋업
  - 로컬 환경에서 구동 설정
- [X] backend 개발 환경 셋업
   - 기본 패키지 설치 및 환경 변수 설정
  - 응용 코드(app.ts)와 구동 코드(index.ts) 작성
- [X] frontend 개발 환경 셋업
  - CRA / Craco & tsconfig-paths-webpack-plugin 기본 환경 설정
  - 환경변수 설정
